import { Product, Category } from '@/types';

export const WHATSAPP_NUMBER = '5527998535551';

export const STORE_CATEGORIES = [
  'Camisetas CW',
  'Camisas CW',
  'Calça CW',
  'Chaveiros CW',
  'Acessórios CW',
];

export const INITIAL_CATEGORIES: Category[] = STORE_CATEGORIES.map((cat, idx) => ({
  id: `cat-${idx + 1}`,
  name: cat,
  slug: cat.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''),
}));

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: '0',
    numId: 0,
    ref: '01/25',
    name: 'CW Andorinhas Black',
    slug: 'cw-andorinhas-black',
    cat: 'Camisetas CW',
    collection: 'Sanctum',
    sub: 'Algodão 240g/m² Oversized',
    description: 'Camiseta com modelagem Oversized confeccionada em malha 100% Algodão, com gramatura de 240g/m².',
    price: 139.90,
    imageUrl: '/images/product-0.webp',
    img: '/images/product-0.webp',
    about: 'Camiseta com modelagem Oversized confeccionada em malha 100% Algodão, com gramatura de 240g/m².',
    composition: '100% Algodão, malha 240g/m².',
    sizes: ['M', 'G', 'GG'],
    sizeMatrix: [{ s: 'M', q: 5 }, { s: 'G', q: 5 }, { s: 'GG', q: 5 }],
    inStock: true,
    isFeatured: true,
    categoryId: 'cat-1',
    categoryName: 'Camisetas CW',
  },
  {
    id: '1',
    numId: 1,
    ref: '02/25',
    name: 'CW Backlog',
    slug: 'cw-backlog',
    cat: 'Camisetas CW',
    collection: 'Sanctum',
    sub: 'Algodão 240g/m² Oversized',
    description: 'Camiseta com modelagem Oversized confeccionada em malha 100% Algodão, com gramatura de 240g/m².',
    price: 139.90,
    imageUrl: '/images/product-1.webp',
    img: '/images/product-1.webp',
    about: 'Camiseta com modelagem Oversized confeccionada em malha 100% Algodão, com gramatura de 240g/m².',
    composition: '100% Algodão, malha 240g/m².',
    sizes: ['M', 'G', 'GG'],
    sizeMatrix: [{ s: 'M', q: 5 }, { s: 'G', q: 5 }, { s: 'GG', q: 5 }],
    inStock: true,
    isFeatured: true,
    categoryId: 'cat-1',
    categoryName: 'Camisetas CW',
  },
  {
    id: '2',
    numId: 2,
    ref: '03/25',
    name: 'CW Andorinha White',
    slug: 'cw-andorinha-white',
    cat: 'Camisetas CW',
    collection: 'Sanctum',
    sub: 'Algodão 240g/m² Oversized',
    description: 'Camiseta com modelagem Oversized confeccionada em malha 100% Algodão, com gramatura de 240g/m².',
    price: 139.90,
    imageUrl: '/images/product-2.webp',
    img: '/images/product-2.webp',
    about: 'Camiseta com modelagem Oversized confeccionada em malha 100% Algodão, com gramatura de 240g/m².',
    composition: '100% Algodão, malha 240g/m².',
    sizes: ['M', 'G', 'GG'],
    sizeMatrix: [{ s: 'M', q: 5 }, { s: 'G', q: 5 }, { s: 'GG', q: 5 }],
    inStock: true,
    isFeatured: true,
    categoryId: 'cat-1',
    categoryName: 'Camisetas CW',
  },
  {
    id: '3',
    numId: 3,
    ref: '04/25',
    name: 'CW Arabic',
    slug: 'cw-arabic',
    cat: 'Camisetas CW',
    collection: 'Sanctum',
    sub: 'Algodão 240g/m² Oversized',
    description: 'Camiseta com modelagem Oversized confeccionada em malha 100% Algodão, com gramatura de 240g/m².',
    price: 139.90,
    imageUrl: '/images/product-3.webp',
    img: '/images/product-3.webp',
    about: 'Camiseta com modelagem Oversized confeccionada em malha 100% Algodão, com gramatura de 240g/m².',
    composition: '100% Algodão, malha 240g/m².',
    sizes: ['M', 'G', 'GG'],
    sizeMatrix: [{ s: 'M', q: 5 }, { s: 'G', q: 5 }, { s: 'GG', q: 5 }],
    inStock: true,
    isFeatured: true,
    categoryId: 'cat-1',
    categoryName: 'Camisetas CW',
  },
];
